CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DTNASC DATE NOT NULL,
    FONE CHAR(11)
);

ALTER TABLE cliente add constraint CLIENTE_PK primary key(ID_CLIENTE);

CREATE TABLE ITENS_VENDA(
	IDVENDA INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    QTDE INT NOT NULL    
);

ALTER TABLE ITENS_VENDA add constraint ITENS_VENDA_PK primary key(IDVENDA, IDPRODUTO);

CREATE TABLE MARCA(
	IDMARCA INT NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

ALTER TABLE MARCA add constraint MARCA_PK primary key(IDMARCA);


CREATE TABLE MODELO(
	IDMOD INT NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    MARCA_IDMARCA INT NOT NULL
);

ALTER TABLE MODELO add constraint MODELO_PK primary key(IDMOD);

CREATE TABLE PESSOA_FISICA(
	CLIENTE_ID INT NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF CHAR(11) NOT NULL
);

ALTER TABLE PESSOA_FISICA add constraint PFISICA_PK primary key(CLIENTE_ID);

CREATE TABLE PESSOA_JURIDICA(
	CLIENTE_ID INT NOT NULL,
    CNPJ VARCHAR(15) NOT NULL,
    IE varchar(20)
);

ALTER TABLE PESSOA_JURIDICA add constraint PESSOA_JURIDICA_PK primary key(CLIENTE_ID);

CREATE TABLE PRODUTO(
	IDPROD INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    DESCRICAO VARCHAR(255),
    QTDE_ESTOQUE INT NOT NULL,
    QTDE_MIN INT NOT NULL,
    MODELO_IDMOD INT NOT NULL
);

ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PK primary key (IDPROD);
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_UN UNIQUE (MODELO_IDMOD);

CREATE TABLE VENDA(
	IDVENDA INT NOT NULL,
    DTVENDA DATE,
    CLIENTE_ID INT NOT NULL
    
);

ALTER TABLE VENDA ADD CONSTRAINT VENDA_PK primary key (IDVENDA);