-- Criando usuário admin para a instância de BD.

CREATE USER 'FELLIPEMELO'@'LOCALHOST' identified BY '123456';
-- CONCEDENDO PERMISSIONAMENTO
-- ACESSO GLOBAL
GRANT SELECT 
ON *.*
TO FELLIPEMELO@LOCALHOST;

